### ISSUE TITLE
Component - UserProfile

### ISSUE THREAD

**Issue by nickyjhong** [2206-fsa-gs-team-gemini/baked#14]
[ x ] Show name (Welcome, NAME)
[ x ] View past orders

**Comment by mscherryxu** [comment]
[ ] If logged in, show profile info
[ ] If not logged in, show login/signup page
[ x ] Create css file

**Comment by nickyjhong** [comment]
Issue: TIER 2: UPDATE INFO **worry about this later**
Currently slug shows up as "profile/:id" -> not properly linked

Affiliated parts:
`client/component/UpdateUser`
`client/store/singleUser` -> update user
`client/Routes.js` -> line 28 (/users/:id)
`server/api/users.js` -> put route

**Comment by nickyjhong** [comment]
Super weird thing I found:

`client/store/Routes.js` -> `<Route path="/users/:id" component={UserProfile} />`
`client/components/Navbar.js` -> `<Link to={`/user/${id}`} className="navLink">Profile</Link>`

CSS breaks

**Comment by nickyjhong** [comment]
I think this might be done but we need to test to make sure converted (open to closed) orders also show and that we can only see own orders/cart
